# Generated by Django 3.0.2 on 2020-01-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesIndex',
            fields=[
                ('series_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('front_identifier', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TiieIndex',
            fields=[
                ('tiie_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('term', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
